//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesDbContext : DbContext
    {
        public EntitiesDbContext()
            : base("name=EntitiesDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contraseña> contraseña { get; set; }
        public virtual DbSet<recordatorio> recordatorio { get; set; }
        public virtual DbSet<simple> simple { get; set; }
        public virtual DbSet<tarea> tarea { get; set; }
        public virtual DbSet<tipoUsuario> tipoUsuario { get; set; }
        public virtual DbSet<TurnoMedico> TurnoMedico { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
