//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class recordatorio
    {
        public int id { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string detalle { get; set; }
        public int usuario { get; set; }
    
        public virtual simple simple { get; set; }
        public virtual TurnoMedico TurnoMedico { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
