//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurnoMedico
    {
        public int id_recordatorio { get; set; }
        public string especialidad { get; set; }
        public string medico { get; set; }
        public string establecimiento { get; set; }
        public string direccion { get; set; }
    
        public virtual recordatorio recordatorio { get; set; }
    }
}
